"""Catalogo stringhe UI IT/EN e helper `t` (fondamenta lingua applicazione)."""

from typing import Literal

LINGUE = ("it", "en")

STRINGS: dict[str, dict[str, str]] = {
    "it": {
        "btn_apri": "Apri file/PDF",
        "btn_incolla": "Incolla",
        "btn_schermo": "Screenshot",
        "btn_annulla": "Annulla",
        "btn_copia": "Copia",
        "btn_salva": "Salva .md",
        "btn_mostra_tutte": "Mostra tutto",
        "btn_impostazioni": "Impostazioni",
        "btn_tema": "Tema: {nome}",
        "testo_vuoto": "Apri un Documento (immagine o PDF) per iniziare.\n\nSorgenti: file • appunti • screenshot.",
        "nessun_documento": "Nessun Documento",
        "progress_formato": "Pagina %v di %m",
        "status_pronto": "pronto",
        "banner_motore_non_pronto": "Motore non pronto: backend non avviato.",
        "banner_errore": "Errore: {dettaglio}",
        "banner_appunti_vuoti": "Appunti vuoti: nessuna immagine.",
        "banner_fallback_cpu": "Pagina {id} elaborata via CPU (fallback)",
        "banner_fallback_cpu_motivo": "Pagina {id} elaborata via CPU (fallback): {motivo}",
        "banner_annullamento": "Annullamento richiesto: finisco la Pagina corrente.",
        "fallback_motivo_auth": "Autenticazione fallita ({codice}): verifica il Token API nelle Impostazioni",
        "fallback_motivo_quota": "Limite chiave superato (403): gestisci la quota su openrouter.ai/keys",
        "fallback_motivo_rate": "Troppe richieste (429): il servizio esterno è sovraccarico, riprova tra poco",
        "fallback_motivo_bad_request": "Richiesta non valida (400): il server esterno non ha compreso il formato",
        "fallback_motivo_server": "Errore del server esterno ({codice}): riprova più tardi",
        "fallback_motivo_timeout": "Timeout: il server esterno non risponde",
        "fallback_motivo_conn": "Server non raggiungibile: verifica l'URL e che il server sia avviato",
        "fallback_motivo_vuoto": "Nessun testo estratto dal modello",
        "fallback_motivo_modello": "Modello non trovato: verifica il nome del modello nelle Impostazioni",
        "fallback_motivo_generico": "Errore del modello: {dettaglio}",
        "motivo_anomalia_eco": "output anomalo: eco del prompt",
        "motivo_anomalia_escape": "output anomalo: escape eccessivi",
        "motivo_anomalia_loop": "output anomalo: ripetizione in loop",
        "motivo_anomalia_loop_parola": "output anomalo: ripetizione in loop (parola dominante)",
        "motivo_anomalia_loop_frasi": "output anomalo: ripetizione in loop (frasi uguali)",
        "motivo_anomalia_senza_contenuto": "output anomalo: testo senza contenuto",
        "motivo_anomalia_compressione": "output anomalo: compressione anomala (loop)",
        "motivo_anomalia_lingua": "output anomalo: lingua inattesa",
        "motivo_anomalia_meta": "output anomalo: meta-discorso ({dettaglio})",
        "motivo_segnale_debole": "segnale debole ({dettaglio})",
        "motivo_anomalia_troncamento": "output anomalo: troncamento (finale monco)",
        "motivo_anomalia_simboli": "output anomalo: simboli inattesi",
        "motivo_output_vuoto": "output vuoto/anomalo",
        "motivo_fail_fast": "fail-fast (senza retry)",
        "motivo_sorgente_nessuno": "sorgente=nessuno",
        "motivo_fallback_vuoto": "fallback vuoto",
        "motivo_fallback_debole": "fallback debole ({n} char)",
        "elaborazione_in_corso": "Elaborazione in corso…",
        "dialogo_apri_titolo": "Apri immagine o PDF",
        "dialogo_apri_filtro": "Documenti (*.png *.jpg *.jpeg *.pdf)",
        "salva_titolo": "Salva",
        "salva_messaggio": "Scegli un file da dialogo (non in test).",
        "dialogo_salva_titolo": "Salva estrazione",
        "dialogo_salva_filtro": "Markdown (*.md)",
        "riga_pagina": "Pagina {id} • {motore} • {tempo}",
        "motore_locale": "GPU locale",
        "motore_esterno_generico": "Server esterno",
        "motore_cpu": "CPU",
        "blocco_pagina": "## Pagina {id}\n\n{testo}",
        "doc_titolo_pagine": "{base} — {n} pagine",
        "doc_nome_immagini": "{n} immagini",
        "sorgente_bundlato": "GPU locale",
        "sorgente_esterno": "esterno",
        "sorgente_nessuno": "nessuno",
        "dettaglio_solo_cpu": "solo CPU",
        "pill_formato": "{etichetta} • {dettaglio}",
        "dlg_impostazioni_titolo": "Impostazioni LocalLens",
        "etichetta_sorgente": "Sorgente modello",
        "etichetta_url": "URL server",
        "etichetta_token": "Token API",
        "token_placeholder": "sk-... — solo questa sessione, non viene salvato",
        "token_tooltip": "Il token vive solo in memoria e viene pulito alla chiusura.",
        "etichetta_modello": "Modello",
        "etichetta_prompt": "Prompt",
        "etichetta_lingue": "Lingue filtro (it,en)",
        "etichetta_soglia": "Soglia righe loop",
        "etichetta_ignora_eco": "Eco del prompt (solo caso raro)",
        "checkbox_istruzioni": "Le istruzioni sono stampate nella Pagina",
        "aiuto_lingue": "Lingue ammesse nel testo trascritto, separate da virgola (es. it,en). Una Pagina scritta in altre lingue viene scartata e riprocessata con Tesseract.",
        "aiuto_soglia": "Numero minimo di righe identiche oltre il quale l'output del modello è considerato un loop degenere. Alzalo su Documenti legittimamente ripetitivi (verbali, elenchi).",
        "aiuto_eco": "Solo se nella Pagina si vedono stampate le istruzioni (es. foto di uno schermo con “Transcribe…”). Se lo attivi su un Documento normale, un errore del modello che ripete le istruzioni verrà accettato come testo invece di essere scartato e riprocessato. Default: spento.",
        "avviso_privacy_esterno": "Attenzione privacy: l'URL non punta alla rete locale, immagini e testo lasceranno questa macchina.",
        "tooltip_aiuto": "Mostra la spiegazione",
        "banner_gpu_non_rilevata": "GPU locale non rilevata (binari o pesi assenti): uso il server esterno.",
        "banner_privacy_url": "Attenzione privacy: l'URL non punta alla rete locale.",
        "motivo_solo_tesseract": "scelta utente: solo Tesseract",
        "stato_esterno": "esterno • {url}",
        "stato_esterno_non_configurato": "esterno (non configurato)",
        "banner_esterno_non_configurato": "Esterno non configurato: inserisci modello e Token API nelle Impostazioni.",
        "motivo_esterno_manca_modello": "esterno non configurato: manca il modello",
        "motivo_esterno_manca_token": "esterno non configurato: manca il Token API",
        "motivo_esterno_manca_modello_token": "esterno non configurato: mancano modello e Token API",
        "stato_gpu_locale": "GPU locale • {url}",
        "stato_nessuno": "nessuno (solo CPU)",
        "stato_gpu_solo_cpu": "GPU locale (solo CPU)",
        "motivo_gpu_non_raggiungibile": "GPU locale non raggiungibile: {url}",
        "banner_solo_cpu_assente": "Solo CPU: server assente su {url}. Avvia il server (llama-server) su quell'URL e riprova.",
        "etichetta_lingua": "Lingua applicazione",
        "lingua_nome_it": "Italiano",
        "lingua_nome_en": "Inglese",
        "tema_nome_chiaro": "chiaro",
        "tema_nome_scuro": "scuro",
    },
    "en": {
        "btn_apri": "Open file/PDF",
        "btn_incolla": "Paste",
        "btn_schermo": "Screenshot",
        "btn_annulla": "Cancel",
        "btn_copia": "Copy",
        "btn_salva": "Save .md",
        "btn_mostra_tutte": "Show all",
        "btn_impostazioni": "Settings",
        "btn_tema": "Theme: {nome}",
        "testo_vuoto": "Open a Document (image or PDF) to begin.\n\nSources: file • clipboard • screenshot.",
        "nessun_documento": "No Document",
        "progress_formato": "Page %v of %m",
        "status_pronto": "ready",
        "banner_motore_non_pronto": "Engine not ready: backend not started.",
        "banner_errore": "Error: {dettaglio}",
        "banner_appunti_vuoti": "Clipboard empty: no image.",
        "banner_fallback_cpu": "Page {id} processed via CPU (fallback)",
        "banner_fallback_cpu_motivo": "Page {id} processed via CPU (fallback): {motivo}",
        "banner_annullamento": "Cancellation requested: finishing the current Page.",
        "fallback_motivo_auth": "Authentication failed ({codice}): check your API token in Settings",
        "fallback_motivo_quota": "Key limit exceeded (403): manage your quota at openrouter.ai/keys",
        "fallback_motivo_rate": "Too many requests (429): external service is busy, try again shortly",
        "fallback_motivo_bad_request": "Bad request (400): external server could not understand the format",
        "fallback_motivo_server": "External server error ({codice}): try again later",
        "fallback_motivo_timeout": "Timeout: external server not responding",
        "fallback_motivo_conn": "Server unreachable: check the URL and that the server is running",
        "fallback_motivo_vuoto": "No text extracted from model",
        "fallback_motivo_modello": "Model not found: check the model name in Settings",
        "fallback_motivo_generico": "Model error: {dettaglio}",
        "motivo_anomalia_eco": "anomalous output: prompt echo",
        "motivo_anomalia_escape": "anomalous output: excessive escapes",
        "motivo_anomalia_loop": "anomalous output: loop repetition",
        "motivo_anomalia_loop_parola": "anomalous output: loop repetition (dominant word)",
        "motivo_anomalia_loop_frasi": "anomalous output: loop repetition (identical sentences)",
        "motivo_anomalia_senza_contenuto": "anomalous output: empty content",
        "motivo_anomalia_compressione": "anomalous output: anomalous compression (loop)",
        "motivo_anomalia_lingua": "anomalous output: unexpected language",
        "motivo_anomalia_meta": "anomalous output: meta-discourse ({dettaglio})",
        "motivo_segnale_debole": "weak signal ({dettaglio})",
        "motivo_anomalia_troncamento": "anomalous output: truncation (incomplete ending)",
        "motivo_anomalia_simboli": "anomalous output: unexpected symbols",
        "motivo_output_vuoto": "empty/anomalous output",
        "motivo_fail_fast": "fail-fast (no retry)",
        "motivo_sorgente_nessuno": "source=none",
        "motivo_fallback_vuoto": "empty fallback",
        "motivo_fallback_debole": "weak fallback ({n} chars)",
        "elaborazione_in_corso": "Processing…",
        "dialogo_apri_titolo": "Open image or PDF",
        "dialogo_apri_filtro": "Documents (*.png *.jpg *.jpeg *.pdf)",
        "salva_titolo": "Save",
        "salva_messaggio": "Choose a file from the dialog (not in tests).",
        "dialogo_salva_titolo": "Save extraction",
        "dialogo_salva_filtro": "Markdown (*.md)",
        "riga_pagina": "Page {id} • {motore} • {tempo}",
        "motore_locale": "Local GPU",
        "motore_esterno_generico": "External server",
        "motore_cpu": "CPU",
        "blocco_pagina": "## Page {id}\n\n{testo}",
        "doc_titolo_pagine": "{base} — {n} pages",
        "doc_nome_immagini": "{n} images",
        "sorgente_bundlato": "Local GPU",
        "sorgente_esterno": "external",
        "sorgente_nessuno": "none",
        "dettaglio_solo_cpu": "CPU only",
        "pill_formato": "{etichetta} • {dettaglio}",
        "dlg_impostazioni_titolo": "LocalLens Settings",
        "etichetta_sorgente": "Model source",
        "etichetta_url": "Server URL",
        "etichetta_token": "API token",
        "token_placeholder": "sk-... — this session only, not saved",
        "token_tooltip": "The token lives only in memory and is cleared on close.",
        "etichetta_modello": "Model",
        "etichetta_prompt": "Prompt",
        "etichetta_lingue": "Filter languages (it,en)",
        "etichetta_soglia": "Loop lines threshold",
        "etichetta_ignora_eco": "Prompt echo (rare case only)",
        "checkbox_istruzioni": "Instructions are printed in the Page",
        "aiuto_lingue": "Languages allowed in the transcribed text, comma-separated (e.g. it,en). A Page written in other languages is discarded and reprocessed with Tesseract.",
        "aiuto_soglia": "Minimum number of identical lines above which the model output is considered a degenerate loop. Raise it for legitimately repetitive Documents (minutes, lists).",
        "aiuto_eco": "Only if the instructions are visibly printed in the Page (e.g. a photo of a screen showing “Transcribe…”). If enabled on a normal Document, a model error repeating the instructions will be accepted as text instead of being discarded and reprocessed. Default: off.",
        "avviso_privacy_esterno": "Privacy warning: the URL does not point to the local network, images and text will leave this machine.",
        "tooltip_aiuto": "Show explanation",
        "banner_gpu_non_rilevata": "Local GPU not detected (binaries or weights missing): using the external server.",
        "banner_privacy_url": "Privacy warning: the URL does not point to the local network.",
        "motivo_solo_tesseract": "user choice: Tesseract only",
        "stato_esterno": "external • {url}",
        "stato_esterno_non_configurato": "external (not configured)",
        "banner_esterno_non_configurato": "External not configured: enter the model and API token in Settings.",
        "motivo_esterno_manca_modello": "external not configured: missing model",
        "motivo_esterno_manca_token": "external not configured: missing API token",
        "motivo_esterno_manca_modello_token": "external not configured: missing model and API token",
        "stato_gpu_locale": "Local GPU • {url}",
        "stato_nessuno": "none (CPU only)",
        "stato_gpu_solo_cpu": "Local GPU (CPU only)",
        "motivo_gpu_non_raggiungibile": "Local GPU unreachable: {url}",
        "banner_solo_cpu_assente": "CPU only: no server at {url}. Start the server (llama-server) at that URL and try again.",
        "etichetta_lingua": "Application language",
        "lingua_nome_it": "Italian",
        "lingua_nome_en": "English",
        "tema_nome_chiaro": "Light",
        "tema_nome_scuro": "Dark",
    },
}


Chiave = Literal[
    "btn_apri",
    "btn_incolla",
    "btn_schermo",
    "btn_annulla",
    "btn_copia",
    "btn_salva",
    "btn_mostra_tutte",
    "btn_impostazioni",
    "btn_tema",
    "testo_vuoto",
    "nessun_documento",
    "progress_formato",
    "status_pronto",
    "banner_motore_non_pronto",
    "banner_errore",
    "banner_appunti_vuoti",
    "banner_fallback_cpu",
    "banner_fallback_cpu_motivo",
    "banner_annullamento",
    "fallback_motivo_auth",
    "fallback_motivo_rate",
    "fallback_motivo_bad_request",
    "fallback_motivo_server",
    "fallback_motivo_timeout",
    "fallback_motivo_conn",
    "fallback_motivo_vuoto",
    "fallback_motivo_modello",
    "fallback_motivo_quota",
    "fallback_motivo_generico",
    "motivo_anomalia_eco",
    "motivo_anomalia_escape",
    "motivo_anomalia_loop",
    "motivo_anomalia_loop_parola",
    "motivo_anomalia_loop_frasi",
    "motivo_anomalia_senza_contenuto",
    "motivo_anomalia_compressione",
    "motivo_anomalia_lingua",
    "motivo_anomalia_meta",
    "motivo_segnale_debole",
    "motivo_anomalia_troncamento",
    "motivo_anomalia_simboli",
    "motivo_output_vuoto",
    "motivo_fail_fast",
    "motivo_sorgente_nessuno",
    "motivo_fallback_vuoto",
    "motivo_fallback_debole",
    "elaborazione_in_corso",
    "dialogo_apri_titolo",
    "dialogo_apri_filtro",
    "salva_titolo",
    "salva_messaggio",
    "dialogo_salva_titolo",
    "dialogo_salva_filtro",
    "riga_pagina",
    "motore_locale",
    "motore_esterno_generico",
    "motore_cpu",
    "blocco_pagina",
    "doc_titolo_pagine",
    "doc_nome_immagini",
    "sorgente_bundlato",
    "sorgente_esterno",
    "sorgente_nessuno",
    "dettaglio_solo_cpu",
    "pill_formato",
    "dlg_impostazioni_titolo",
    "etichetta_sorgente",
    "etichetta_url",
    "etichetta_token",
    "token_placeholder",
    "token_tooltip",
    "etichetta_modello",
    "etichetta_prompt",
    "etichetta_lingue",
    "etichetta_soglia",
    "etichetta_ignora_eco",
    "checkbox_istruzioni",
    "aiuto_lingue",
    "aiuto_soglia",
    "aiuto_eco",
    "avviso_privacy_esterno",
    "tooltip_aiuto",
    "banner_gpu_non_rilevata",
    "banner_privacy_url",
    "motivo_solo_tesseract",
    "stato_esterno",
    "stato_esterno_non_configurato",
    "banner_esterno_non_configurato",
    "motivo_esterno_manca_modello",
    "motivo_esterno_manca_token",
    "motivo_esterno_manca_modello_token",
    "stato_gpu_locale",
    "stato_nessuno",
    "stato_gpu_solo_cpu",
    "motivo_gpu_non_raggiungibile",
    "banner_solo_cpu_assente",
    "etichetta_lingua",
    "lingua_nome_it",
    "lingua_nome_en",
    "tema_nome_chiaro",
    "tema_nome_scuro",
]

SORGENTE_LABELS: dict[str, str] = {
    "bundlato": "sorgente_bundlato",
    "esterno": "sorgente_esterno",
    "nessuno": "sorgente_nessuno",
}

# Compat: alias storico usato da finestra/impostazioni prima della centralizzazione
_CHIAVE_SORGENTE = SORGENTE_LABELS


class LinguaService:
    """Service typed per LinguaInterfaccia: seam LinguaInterfaccia."""

    def __init__(self, lingua: str = "en") -> None:
        self._lingua = lingua if lingua in LINGUE else "en"

    def t(self, chiave: Chiave, **fmt) -> str:  # type: ignore[valid-type]
        tabella = STRINGS.get(self._lingua) or STRINGS["en"]
        return tabella[chiave].format(**fmt)  # type: ignore[index]

    def set_lingua(self, lingua: str) -> None:
        self._lingua = lingua if lingua in LINGUE else "en"

    @property
    def lingua(self) -> str:
        return self._lingua


def t(lingua: str, chiave: str, **fmt) -> str:
    """Compat shim: delega a LinguaService (fondamenta lingua applicazione)."""
    return LinguaService(lingua).t(chiave, **fmt)  # type: ignore[arg-type]


def traduce_motivo(lingua: str, motivo: str) -> str:
    """Traduce la nota/motivo pipeline (sempre IT raw) nella lingua UI."""
    if not motivo or lingua == "it":
        return motivo
    import re

    # mappa IT raw -> chiave catalogo (con eventuale estrazione param)
    # ordine: pattern più specifici prima
    frammenti = [f.strip() for f in motivo.split(";") if f.strip()]
    tradotti: list[str] = []
    for frag in frammenti:
        low = frag.strip()
        # fallback per "output vuoto/anomalo" ecc. mappiamo exact
        mappa_esatta = {
            "output anomalo: eco del prompt": "motivo_anomalia_eco",
            "output anomalo: escape eccessivi": "motivo_anomalia_escape",
            "output anomalo: ripetizione in loop": "motivo_anomalia_loop",
            "output anomalo: ripetizione in loop (parola dominante)": "motivo_anomalia_loop_parola",
            "output anomalo: ripetizione in loop (frasi uguali)": "motivo_anomalia_loop_frasi",
            "output anomalo: testo senza contenuto": "motivo_anomalia_senza_contenuto",
            "output anomalo: compressione anomala (loop)": "motivo_anomalia_compressione",
            "output anomalo: lingua inattesa": "motivo_anomalia_lingua",
            "output anomalo: troncamento (finale monco)": "motivo_anomalia_troncamento",
            "output anomalo: simboli inattesi": "motivo_anomalia_simboli",
            "output vuoto/anomalo": "motivo_output_vuoto",
            "fail-fast (senza retry)": "motivo_fail_fast",
            "sorgente=nessuno": "motivo_sorgente_nessuno",
            "fallback vuoto": "motivo_fallback_vuoto",
        }
        if low in mappa_esatta:
            tradotti.append(t(lingua, mappa_esatta[low]))
            continue
        # param: meta-discorso
        m = re.match(r"^output anomalo: meta-discorso \((.*)\)$", low)
        if m:
            tradotti.append(t(lingua, "motivo_anomalia_meta", dettaglio=m.group(1)))
            continue
        m = re.match(r"^segnale debole \((.*)\)$", low)
        if m:
            tradotti.append(t(lingua, "motivo_segnale_debole", dettaglio=m.group(1)))
            continue
        m = re.match(r"^fallback debole \((\d+) char\)$", low)
        if m:
            tradotti.append(t(lingua, "motivo_fallback_debole", n=m.group(1)))
            continue
        # non riconosciuto (es. "backend giu", "HTTP 500:...") → lascia com'è
        tradotti.append(frag)
    return "; ".join(tradotti)
