"""Catalogo stringhe UI IT/EN e helper `t` (fondamenta lingua applicazione)."""

LINGUE = ("it", "en")

STRINGS: dict[str, dict[str, str]] = {
    "it": {
        "btn_apri": "Apri file/PDF",
        "btn_incolla": "Incolla",
        "btn_schermo": "Screenshot",
        "btn_annulla": "Annulla",
        "btn_copia": "Copia",
        "btn_salva": "Salva .txt",
        "btn_impostazioni": "Impostazioni",
        "btn_tema": "Tema: {nome}",
        "testo_vuoto": "Apri un Documento (immagine o PDF) per iniziare.\n\nSorgenti: file • appunti • screenshot.",
        "nessun_documento": "Nessun Documento",
        "progress_formato": "Pagina %v di %m",
        "status_pronto": "pronto",
        "banner_motore_non_pronto": "Motore non pronto: backend non avviato.",
        "banner_errore": "Errore: {dettaglio}",
        "banner_appunti_vuoti": "Appunti vuoti: nessuna immagine.",
        "banner_fallback_cpu": "Pagina {id} elaborata via CPU (fallback)",
        "banner_annullamento": "Annullamento richiesto: finisco la Pagina corrente.",
        "elaborazione_in_corso": "Elaborazione in corso…",
        "dialogo_apri_titolo": "Apri immagine o PDF",
        "dialogo_apri_filtro": "Documenti (*.png *.jpg *.jpeg *.pdf)",
        "salva_titolo": "Salva",
        "salva_messaggio": "Scegli un file da dialogo (non in test).",
        "dialogo_salva_titolo": "Salva estrazione",
        "dialogo_salva_filtro": "Testo (*.txt)",
        "riga_pagina": "Pagina {id} • {motore} • {tempo}",
        "blocco_pagina": "── Pagina {id} • {motore} • {tempo} ──\n{testo}",
        "doc_titolo_pagine": "{base} — {n} pagine",
        "doc_nome_immagini": "{n} immagini",
        "sorgente_bundlato": "GPU locale",
        "sorgente_esterno": "esterno",
        "sorgente_nessuno": "nessuno",
        "dettaglio_solo_cpu": "solo CPU",
        "pill_formato": "{etichetta} • {dettaglio}",
        "dlg_impostazioni_titolo": "Impostazioni LocalLens",
        "etichetta_sorgente": "Sorgente modello",
        "etichetta_url": "URL server",
        "etichetta_token": "Token API",
        "etichetta_modello": "Modello",
        "etichetta_prompt": "Prompt",
        "etichetta_lingue": "Lingue filtro (it,en)",
        "etichetta_soglia": "Soglia righe loop",
        "etichetta_ignora_eco": "Ignora eco prompt",
        "checkbox_istruzioni": "Istruzioni stampate nella sorgente",
        "aiuto_lingue": "Lingue ammesse nel testo trascritto, separate da virgola (es. it,en). Una Pagina scritta in altre lingue viene scartata e riprocessata con Tesseract.",
        "aiuto_soglia": "Numero minimo di righe identiche oltre il quale l'output del modello è considerato un loop degenere. Alzalo su Documenti legittimamente ripetitivi (verbali, elenchi).",
        "aiuto_eco": "Attivalo se le istruzioni di trascrizione sono stampate nel Documento: evita che la loro presenza faccia scartare una trascrizione valida.",
        "avviso_privacy_esterno": "Attenzione privacy: l'URL non punta alla rete locale, immagini e testo lasceranno questa macchina.",
        "tooltip_aiuto": "Mostra la spiegazione",
        "banner_gpu_non_rilevata": "GPU locale non rilevata (binari o pesi assenti): uso il server esterno.",
        "banner_privacy_url": "Attenzione privacy: l'URL non punta alla rete locale.",
        "motivo_solo_tesseract": "scelta utente: solo Tesseract",
        "stato_esterno": "esterno • {url}",
        "stato_gpu_locale": "GPU locale • {url}",
        "stato_nessuno": "nessuno (solo CPU)",
        "stato_gpu_solo_cpu": "GPU locale (solo CPU)",
        "motivo_gpu_non_raggiungibile": "GPU locale non raggiungibile: {url}",
        "banner_solo_cpu_assente": "Solo CPU: server assente su {url}",
        "etichetta_lingua": "Lingua applicazione",
        "lingua_nome_it": "Italiano",
        "lingua_nome_en": "Inglese",
        "tema_nome_chiaro": "chiaro",
        "tema_nome_scuro": "scuro",
    },
    "en": {
        "btn_apri": "Open file/PDF",
        "btn_incolla": "Paste",
        "btn_schermo": "Screenshot",
        "btn_annulla": "Cancel",
        "btn_copia": "Copy",
        "btn_salva": "Save .txt",
        "btn_impostazioni": "Settings",
        "btn_tema": "Theme: {nome}",
        "testo_vuoto": "Open a Document (image or PDF) to begin.\n\nSources: file • clipboard • screenshot.",
        "nessun_documento": "No Document",
        "progress_formato": "Page %v of %m",
        "status_pronto": "ready",
        "banner_motore_non_pronto": "Engine not ready: backend not started.",
        "banner_errore": "Error: {dettaglio}",
        "banner_appunti_vuoti": "Clipboard empty: no image.",
        "banner_fallback_cpu": "Page {id} processed via CPU (fallback)",
        "banner_annullamento": "Cancellation requested: finishing the current Page.",
        "elaborazione_in_corso": "Processing…",
        "dialogo_apri_titolo": "Open image or PDF",
        "dialogo_apri_filtro": "Documents (*.png *.jpg *.jpeg *.pdf)",
        "salva_titolo": "Save",
        "salva_messaggio": "Choose a file from the dialog (not in tests).",
        "dialogo_salva_titolo": "Save extraction",
        "dialogo_salva_filtro": "Text (*.txt)",
        "riga_pagina": "Page {id} • {motore} • {tempo}",
        "blocco_pagina": "── Page {id} • {motore} • {tempo} ──\n{testo}",
        "doc_titolo_pagine": "{base} — {n} pages",
        "doc_nome_immagini": "{n} images",
        "sorgente_bundlato": "Local GPU",
        "sorgente_esterno": "external",
        "sorgente_nessuno": "none",
        "dettaglio_solo_cpu": "CPU only",
        "pill_formato": "{etichetta} • {dettaglio}",
        "dlg_impostazioni_titolo": "LocalLens Settings",
        "etichetta_sorgente": "Model source",
        "etichetta_url": "Server URL",
        "etichetta_token": "API token",
        "etichetta_modello": "Model",
        "etichetta_prompt": "Prompt",
        "etichetta_lingue": "Filter languages (it,en)",
        "etichetta_soglia": "Loop lines threshold",
        "etichetta_ignora_eco": "Ignore prompt echo",
        "checkbox_istruzioni": "Instructions printed in the source",
        "aiuto_lingue": "Languages allowed in the transcribed text, comma-separated (e.g. it,en). A Page written in other languages is discarded and reprocessed with Tesseract.",
        "aiuto_soglia": "Minimum number of identical lines above which the model output is considered a degenerate loop. Raise it for legitimately repetitive Documents (minutes, lists).",
        "aiuto_eco": "Enable it if the transcription instructions are printed in the Document: prevents their presence from discarding a valid transcription.",
        "avviso_privacy_esterno": "Privacy warning: the URL does not point to the local network, images and text will leave this machine.",
        "tooltip_aiuto": "Show explanation",
        "banner_gpu_non_rilevata": "Local GPU not detected (binaries or weights missing): using the external server.",
        "banner_privacy_url": "Privacy warning: the URL does not point to the local network.",
        "motivo_solo_tesseract": "user choice: Tesseract only",
        "stato_esterno": "external • {url}",
        "stato_gpu_locale": "Local GPU • {url}",
        "stato_nessuno": "none (CPU only)",
        "stato_gpu_solo_cpu": "Local GPU (CPU only)",
        "motivo_gpu_non_raggiungibile": "Local GPU unreachable: {url}",
        "banner_solo_cpu_assente": "CPU only: no server at {url}",
        "etichetta_lingua": "Application language",
        "lingua_nome_it": "Italian",
        "lingua_nome_en": "English",
        "tema_nome_chiaro": "Light",
        "tema_nome_scuro": "Dark",
    },
}


def t(lingua: str, chiave: str, **fmt) -> str:
    """Rende STRINGS[lingua][chiave].format(**fmt); lingua ignota → "it"."""
    tabella = STRINGS.get(lingua) or STRINGS["it"]
    return tabella[chiave].format(**fmt)
